from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import warnings
import pymysql
import time

DB_HOST = '10.11.2.21'
DB_USER = 'root'
DB_PASS = '!QAZxsw2'
DATABASE = 'erp_collect'
DB_PORT = 3306


def query_product():
    connect = pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASS, db=DATABASE, port=DB_PORT)
    cursor = connect.cursor()
    query_all_sql = 'select * from amz_product'
    cursor.execute(query_all_sql)
    results = cursor.fetchall()
    return results


def get_amz_cookies(product_url):
    chrome_options = Options()
    # chrome_options.add_argument('window-size=1920x3000') #指定浏览器分辨率
    # 解决DevToolsActivePort文件不存在的报错
    # chrome_options.add_argument('--no-sandbox')
    # 谷歌文档提到需要加上这个属性来规避bug
    # chrome_options.add_argument('--disable-gpu')
    # chrome_options.add_argument('--hide-scrollbars') #隐藏滚动条, 应对一些特殊页面
    # 浏览器不提供可视化页面. linux下如果系统不支持可视化不加这条会启动失败
    # chrome_options.add_argument('--headless')
    # 不加载图片, 提升速度
    chrome_options.add_argument('--user-data-dir=D:\\ud')
    chrome_options.add_argument('blink-settings=imagesEnabled=false')
    chrome_options.add_experimental_option('excludeSwitches', ['enable-automation'])
    warnings.filterwarnings('ignore')
    browser = webdriver.Chrome(chrome_options=chrome_options)
    try:
        browser.get(product_url)
        browser.refresh()
        time.sleep(3)
        print(browser.get_cookies())
        cookie_list = browser.get_cookies()
        cookies = ''
        for cookie in cookie_list[:len(cookie_list) - 1]:
            cookie = cookie['name'] + '=' + cookie['value'] + '; '
            cookies = cookies + cookie
        cookies = cookies + cookie_list[-1]['name'] + '=' + cookie_list[-1]['value']
        print(cookies)
        # with open('cookie.py', 'a', encoding='utf-8')as f:
        #     f.write("COOKIE = '" + cookies + "'")
        #     f.close()
        with open('cookie.py', 'a', encoding='utf-8')as f:
            f.write("'" + cookies.strip() + "'," + '\n')
            f.close()
        browser.quit()
    except:
        browser.get(product_url)
        browser.refresh()
        time.sleep(3)
        print(browser.get_cookies())
        cookie_list = browser.get_cookies()
        cookies = ''
        for cookie in cookie_list[:len(cookie_list) - 1]:
            cookie = cookie['name'] + '=' + cookie['value'] + '; '
            cookies = cookies + cookie
        cookies = cookies + cookie_list[-1]['name'] + '=' + cookie_list[-1]['value']
        print(cookies)
        with open('cookie.py', 'a', encoding='utf-8')as f:
            f.write("'" + cookies.strip() + "'," + '\n')
            f.close()
        # with open('cookie.py', 'w', encoding='utf-8')as f:
        #     f.write("COOKIE = '" + cookies + "'")
        #     f.close()

        browser.quit()


def main():
    # products = query_product()
    products = ['https://www.amazon.com/Remover-Bestdream-Painless-Electric-waterproof/dp/B07S3NS9GJ/',
                'https://www.amazon.com/Silicone-Eyelash-Perming-Reusable-Eyelashing/dp/B07QTKNX98/',
                'https://www.amazon.com/Magnetic-Eyelashes-LIBAO-Eyeliner-Reusable/dp/B07V1MPHKN/',
                'https://www.amazon.com/TygoMall-Professional-Eyeshadow-Disposable-Applicator/dp/B0768RHWGT/',
                'https://www.amazon.com/Lashd-Up-Magnetic-Eyelashes-Reusable/dp/B07DXB4CMQ/',
                'https://www.amazon.com/Mac-Split-Fibre-Blending-Brush/dp/B01N5QX8TH/',
                'https://www.amazon.com/Eyebrow-Spoolie-Professional-Bristle-Necessary/dp/B07RY44RN9/',
                'https://www.amazon.com/BEENLE-Replacement-Finishing-Epilators-Gold-Plated/dp/B07SBWJCPV/',
                'https://www.amazon.com/Tweezerman-Curl-Rose-Eyelash-Curler/dp/B005FBTPL4/',
                'https://www.amazon.com/Larenim-Double-Ended-Colour-Brush/dp/B003EXC4Q8/',
                'https://www.amazon.com/Danielle-Touch-Stainless-Eyelash-Curler/dp/B00FHUB4S0/',
                'https://www.amazon.com/Braun-Silk-%C3%A9pil-LS5160WD-Lady-Shaver/dp/B00BFXRVMQ/',
                'https://www.amazon.com/Baifeng-Plastic-Adjustable-Stretcher-25-32cm/dp/B07FQPXVPL/',
                'https://www.amazon.com/Revlon-Brow-Set-Pack-2/dp/B001ET77N4/',
                'https://www.amazon.com/Panasonic-Eyelashes-Come-Natural-EH-SE10P-P/dp/B0037M8956/',
                'https://www.amazon.com/YOURSMART-Warmer-Removal-Eyebrow-Brazilian/dp/B07VLFJYDJ/',
                'https://www.amazon.com/Leyeet-Rechargeable-Waterproof-Painless-Electric/dp/B07KD7C421/',
                'https://www.amazon.com/Electric-Shaver-Rechargeable-Personal-Trimmer/dp/B07QNTHNXW/',
                'https://www.amazon.com/Lifetop-Professional-Electric-Automatic-Epilator/dp/B01EJSMSCG/',
                'https://www.amazon.com/Eyebrow-Shaper-Razors-Removers-Shavers/dp/B01GUEYK1O/',
                'https://www.amazon.com/Electric-Portable-Painless-Professional-Waterproof/dp/B07QKZ7JBR/',
                'https://www.amazon.com/Real-Techniques-Metals-Collection-Tapered/dp/B01EYT7DVQ/',
                'https://www.amazon.com/BMS-Ultimate-Personal-Shaver-Ladies/dp/B00JOQJL0G/',
                'https://www.amazon.com/Ardell-Faux-Mink-Black-Lashes/dp/B0733YH3KR/',
                'https://www.amazon.com/Remover-Painless-Electric-Removal-Cordless/dp/B07MY4ZBGB/',
                'https://www.amazon.com/Personna-Eyebrow-Shapers-Count-Pack/dp/B01G43PCX6/',
                'https://www.amazon.com/Body-Bare-Personal-Shaver-Bikini/dp/B000F0WAZ8/',
                'https://www.amazon.com/Women%EF%BC%8CPainless-Professional-Electric-Arm%EF%BC%8CWaterproof-Epilator/dp/B07WR11R52/',
                'https://www.amazon.com/Vogcrest-Electric-Painless-Epilator-Portable/dp/B07WFBCZPD/',
                'https://www.amazon.com/NARS-Brow-Shader-Brush-No/dp/B00021DIP6/',
                'https://www.amazon.com/Gracefulvara-Foldable-Stainless-Eyebrow-Eyelash/dp/B06WP96JGC/',
                'https://www.amazon.com/Electric-Underarm-Waterproof-Operated-HYTK/dp/B07FBBCX93/',
                'https://www.amazon.com/EcoTools-Complexion-Coverage-Materials-Foundation/dp/B006J5V6ZI/',
                'https://www.amazon.com/Gillette-Venus-Embrace-Sensitive-Womens/dp/B071S2B392/',
                'https://www.amazon.com/Schick-Quattro-Refills-Sensitive-Hypo-Allergenic/dp/B00EZWT1EA/',
                'https://www.amazon.com/ETUDE-HOUSE-Beauty-Secret-Perfect/dp/B00RBACPWS/',
                'https://www.amazon.com/Schick-Hydro-Silk-Cartridges-Pack/dp/B00MUE9T4C/',
                'https://www.amazon.com/Wax-Necessities-Spatulas-Applicators-100pk/dp/B013LJK3LW/',
                'https://www.amazon.com/Hairdresser-Organizer-Professional-Equipment-Multifunctional/dp/B07MTGDH75/',
                'https://www.amazon.com/Bdellium-Tools-Professional-Makeup-Studio/dp/B002UL10HO/',
                'https://www.amazon.com/Docolor-Kabuki-Foundation-Portable-Cosmetic/dp/B01NCLJUKR/',
                'https://www.amazon.com/Urban-Glow-Retractable-Foundation-Bronzer/dp/B07SB1SB6V/',
                'https://www.amazon.com/Glo-Skin-Beauty-Brush-Flat-top/dp/B00O13WMT4/',
                'https://www.amazon.com/Foundation-Makeup-Brush-Kabuki-DUcare/dp/B07J6BJTPQ/',
                'https://www.amazon.com/Eco-Friendly-Handled-Bamboo-ki-Cruelty-Sustainable/dp/B01C4LC4QA/',
                'https://www.amazon.com/C113-LTH-Rollabout-Laminated-Dina-Meri/dp/B07P8WVN4N/',
                'https://www.amazon.com/Premium-Portable-MODESSE-Perfect-Bridesmaids/dp/B07CYMNP3J/',
                'https://www.amazon.com/Aluminum-Instrument-Chemical-Service-Storage/dp/B07VM6Y7G1/',
                'https://www.amazon.com/Professional-grade-Vegan-Brushes-Kabuki-Brush/dp/B00AN2HLL6/',
                'https://www.amazon.com/Shiseido-perfect-foundation-brush/dp/B005FU9SDU/',
                'https://www.amazon.com/Facocy-Professional-Foundation-Stippling-Concealer/dp/B07S7HDC2L/',
                'https://www.amazon.com/Sigma-Beauty-Kabuki-Makeup-Duo-Fibers/dp/B07DD3JRP9/',
                'https://www.amazon.com/SEPHORA-PRO-Domed-Foundation-Brush/dp/B07GDT25DG/',
                'https://www.amazon.com/Cosmetics-Selfie-Ready-Foundation-Blurring/dp/B019KVYC30/',
                'https://www.amazon.com/HML-Professional-Foundation-Cosmetic-Cosmetics/dp/B072VSVY9S/',
                'https://www.amazon.com/Aguder-Bristles-Retractable-Makeup-Purple/dp/B01M5ASXZ9/',
                'https://www.amazon.com/Studio-Gear-Cosmetics-Foundation-Brush/dp/B0037MHTB6/',
                'https://www.amazon.com/Steamer-Massage-Parlor-Furniture-Equipment/dp/B01EZ7EYK0/',
                'https://www.amazon.com/IDS-Cosmetic-Blender-Foundation-Cosmetics/dp/B07G448N9J/',
                'https://www.amazon.com/Giraffe-X-Sterilizer-Disinfection-Manicure-Equipment/dp/B07L8Z4692/',
                'https://www.amazon.com/NRG-Warmer-Cabinet-Massage-Facial/dp/B009YZ8LDK/',
                'https://www.amazon.com/Foundation-makeup-powder-foundation-stipple/dp/B07G32LLCH/',
                'https://www.amazon.com/tesyyke-Multifunction-Foundation-Concealer-Lasting/dp/B07VF5C3S8/',
                'https://www.amazon.com/Makeup-Toraway-Toothbrush-Foundation-Brushes/dp/B01DG3ITI2/',
                'https://www.amazon.com/ZoePets1pc-Foundation-Makeup-Kabuki-Blending/dp/B07QKF4Q8B/',
                'https://www.amazon.com/TOOGOO-Brushes-Foundation-Portable-Contour/dp/B07RFR8SHS/',
                'https://www.amazon.com/Beauty-Style-Massage-Multi-function-Adjustable/dp/B07C577TXL/',
                'https://www.amazon.com/Luxspire-Professional-Makeup-Foundation-Cosmetics/dp/B0784WNHX1/',
                'https://www.amazon.com/Harvey-Treatment-Stationary-Massage-Acupuncture/dp/B00Q5FCQD8/',
                'https://www.amazon.com/Massage-Stationary-Physical-Therapy-Memory/dp/B00K2OITES/',
                'https://www.amazon.com/Marc-Jacobs-Beauty-Shape-Contour/dp/B00T5Z0OV6/',
                'https://www.amazon.com/Brush-Guard-Highlight-Blush-Clear/dp/B01HBXP95O/',
                'https://www.amazon.com/BR-Beauty-Arctic-Styling-Chair/dp/B01CIN7DMO/',
                'https://www.amazon.com/Chair-High-Back-Adjustable-Executive-Ergonomic-Vibrating/dp/B07KBZ41QM/',
                'https://www.amazon.com/AVANI-59003-Womens-Blush-Brush/dp/B00CQ9YO8M/',
                'https://www.amazon.com/Liberex-Facial-Steamer-Moisturize-Blackheads/dp/B07KYMG8CN/',
                'https://www.amazon.com/Afazfa%F0%9F%92%97%F0%9F%92%97Professional-Makeup-Bronzer-Highlighter-Palette/dp/B07VFFR47C/',
                'https://www.amazon.com/Facial-Silicone-Mixing-Spatula-Mud-Mask/dp/B07F3WR53Z/',
                'https://www.amazon.com/YIIA-Scented-Aromatherapy-Lavender-%EF%BC%8CJasmine%EF%BC%8CVanilla%EF%BC%8CBergamot/dp/B07SVNYGCC/',
                'https://www.amazon.com/PMD-Personal-Microderm-Classic-Microdermabrasion/dp/B00MU3UVFY/',
                'https://www.amazon.com/Wishwin-Portable-Makeup-Brush-Powder/dp/B07VHZ85T3/',
                'https://www.amazon.com/YINUO-LIGHT-Aromatherapy-Anniversary-Valentines/dp/B07QB1ZTJP/',
                'https://www.amazon.com/Natuwax-C01W-35784-Duo-Warmer/dp/B07B6DSHFN/',
                'https://www.amazon.com/Qivange-Brushes-Cosmetic-Highlighter-Professional/dp/B06ZXWSL9J/',
                'https://www.amazon.com/Prosperity-Affirmation-Candle-Essential-Abundance/dp/B07GZZ4XG2/',
                'https://www.amazon.com/Coventry-Creations-AF-SU-Affirmations-Success/dp/B00O4B8OC2/',
                'https://www.amazon.com/MOUJAN-Pre-Waxed-Strips-for-Face/dp/B000142C4M/',
                'https://www.amazon.com/Derma-Roller-Microneedle-Titanium-Needles/dp/B07GCGDVPF/',
                'https://www.amazon.com/Lavender-Scented-Natural-Aromatherapy-Essential/dp/B01N27I76Z/',
                'https://www.amazon.com/Applicator-Sticks-Painless-Depilatory-Lavender/dp/B07DG2YXZH/',
                'https://www.amazon.com/Applicator-Spatula-Epilating-Natural-Eyebrows/dp/B07CYLBZBC/',
                'https://www.amazon.com/Aromatherapy-Scented-Candles-Peppermint-Eucalyptus/dp/B06XP8PYBT/',
                'https://www.amazon.com/PRO-WAX-Heater-Warmer-Beauty-Equipment/dp/B009PV9RU4/',
                'https://www.amazon.com/Aromatherapy-Candles-Natural-Essential-Pomegranate/dp/B07Q31DZ7X/',
                'https://www.amazon.com/Blackhead-Remover-Abody-Electric-Extractor/dp/B07TGCZ71M/',
                'https://www.amazon.com/Burmax-FantaSea-Wax-Warmer/dp/B00TUKDQIY/',
                'https://www.amazon.com/Wooden-Waxing-Applicator-Sticks-Eyebrow/dp/B0145T7O6O/',
                'https://www.amazon.com/IEOKE-Removal-Remover-Machine-Applicator/dp/B078SLD62G/',
                'https://www.amazon.com/MAKARTT-Woven-Removal-Strip-Epilating/dp/B06ZYWF4GH/',
                'https://www.amazon.com/GiGi-Natural-Muslin-Applicator-Combo/dp/B0019QBTLI/',
                'https://www.amazon.com/Aromatherapy-Scented-Candles-Sandalwood-Ounces/dp/B07CPGCRTV/',
                'https://www.amazon.com/Pure-Silk-Shave-Cream-Raspberry/dp/B07L4B3S4T/',
                'https://www.amazon.com/Blackhead-Remover-Comedone-Extractor-Removal/dp/B07S8MSVLZ/',
                'https://www.amazon.com/LCL-Beauty-Professional-Single-Pot-Depilatory/dp/B00NPEDPPK/',
                'https://www.amazon.com/Painless-Lansley-Sensitive-Brazilian-Blueberry/dp/B07TFD6PVN/',
                'https://www.amazon.com/Alba-Botanica-Emollient-Cream-Unscented/dp/B002LN39IE/',
                'https://www.amazon.com/Wax-Necessities-Barbero-Stripless-Waxing/dp/B072R63Y17/',
                'https://www.amazon.com/GiGi-Gigi-Applicators-Small/dp/B00QKHBM4K/',
                'https://www.amazon.com/GiGi-Charcoal-Detox-Facial-Wax/dp/B076CVFN2B/',
                'https://www.amazon.com/Warmer-Removal-Electrict-Flavors-Applicator/dp/B075R3MKXT/',
                'https://www.amazon.com/Wax-Necessities-Heater-Pro-Wax-Colored/dp/B01B2XQ47Q/',
                'https://www.amazon.com/fleur-spa-Massage-Vanilla-Fragrance/dp/B06XD8MKSK/',
                'https://www.amazon.com/No-mo-stache-Hypoallergenic-Waxing-Strips/dp/B076FZ95CQ/',
                'https://www.amazon.com/Massage-Candles-Scented-Eco-Friendly-Vegetable/dp/B07QLW3KVV/',
                'https://www.amazon.com/AF-HE-Affirmations-Healing-Candle/dp/B00TCR8YN2/',
                'https://www.amazon.com/Alba-Botanica-emollient-sunscreen-lavender/dp/B000S83L5A/',
                'https://www.amazon.com/No-Mo-Stache-Portable-Hair-Removal/dp/B0773QFMCP/',
                'https://www.amazon.com/First-Beauty-Smooth-Shave-Cream-2/dp/B0051YNCAU/',
                'https://www.amazon.com/Peppermint-Essential-Yeelen-Applicator-Brazilian/dp/B07RFP9BCH/',
                'https://www.amazon.com/Sanek-Neck-Strips-One-Pack/dp/B00023J4BG/',
                'https://www.amazon.com/Nair-Ultimate-Moroccan-Blossom-Rinseable/dp/B00HKGP9TE/',
                'https://www.amazon.com/Depimiel-Removal-Non-Woven-Waxing-Cloth/dp/B019NM0UEQ/',
                'https://www.amazon.com/SATIN-SMOOTH-Empty-Metal-Pot/dp/B00A5ETEA8/',
                'https://www.amazon.com/Waxing-Non-woven-baotongle-Removal-Applicator/dp/B07BFTQD42/',
                'https://www.amazon.com/Graham-Barber-Stylist-Dispenser-SD-49356/dp/B000QU8RF4/',
                'https://www.amazon.com/Moom-Express-Waxed-Strips-Packages/dp/B001ET7A0E/',
                'https://www.amazon.com/Hair-Off-Remover-Mitten/dp/B00G8EDEZ0/',
                'https://www.amazon.com/Coochy-Shave-Cream-Island-Paradise/dp/B07BC5VK1Z/',
                'https://www.amazon.com/Mirucoo-Non-woven-Facial-Removal-Epilating/dp/B07PYG9C59/',
                'https://www.amazon.com/Bikini-Zone-Moisturizing-Grapefruit-Pomegranate/dp/B07PBX5LSJ/',
                'https://www.amazon.com/Shave-Cream-Moisturizing-Lavender-Jasmine/dp/B00G4DRWNU/',
                'https://www.amazon.com/Giovanni-Moisturizing-Shave-Sensitive-Fragrance/dp/B005JF56LY/',
                'https://www.amazon.com/URPOWER-Essential-Humidifiers-Ultrasonic-Aromatherapy/dp/B074DQKWZ2/',
                'https://www.amazon.com/Essential-Diffuser-Aromatherapy-Diffusers-Humidifiers/dp/B0781STX21/',
                'https://www.amazon.com/Essential-Diffuser-Waterless-Nebulizer-Aromatherapy/dp/B07RV2R9P2/',
                'https://www.amazon.com/Letter-Monogram-Initial-Compact-Cosmetic/dp/B07P7YKDSN/',
                'https://www.amazon.com/KEDSUM-Mirror-Handle-Bathroom-Bedroom/dp/B07NYNC2D8/',
                'https://www.amazon.com/Fityle-Decorative-Antique-Handheld-Embossed/dp/B07Q1VGLJL/',
                'https://www.amazon.com/Source-Acrylic-Safety-Classroom-Camping/dp/B074ZP8LWR/',
                'https://www.amazon.com/Egyptian-Mirror-Collectible-Religious-Symbol/dp/B001S5HTH8/',
                'https://www.amazon.com/Compact-Dynippy-Portable-Double-sided-Magnification/dp/B07VWX4PX2/',
                'https://www.amazon.com/Aufee-Trolley-Practical-Pedestal-Aluminum/dp/B07R1YR75Y/',
                'https://www.amazon.com/Funnylife-Rollabout-Trolley-Lockable-Organizer/dp/B07QWWJPG1/',
                'https://www.amazon.com/Trolley-Hairdresser-Pedestal-Aluminum-Instrument/dp/B07RRMQ6TS/',
                'https://www.amazon.com/ProHairTools-Pedicure-Complete-Rolling-Station/dp/B001VBLGUU/',
                'https://www.amazon.com/Medical-Physician-Roll-About-Lockable-Dina/dp/B07F72KC1Y/',
                'https://www.amazon.com/SierraComfort-Professional-Portable-Massage-Purple/dp/B00F575EF4/',
                'https://www.amazon.com/Artechworks-Professional-Portable-Lightweight-Aluminium/dp/B07Q35SSZX/',
                'https://www.amazon.com/Royal-Massage-Sheffield-Professional-Chiropractic/dp/B079YY6ZR5/',
                'https://www.amazon.com/Black-Portable-Massage-Facial-Renewed/dp/B07Q1D7CRY/',
                'https://www.amazon.com/Dr-lomilomi-Universal-Massage-Cushion-Pillow/dp/B01N164R99/',
                'https://www.amazon.com/Folding-Portable-Adjustable-Professional-Bolsters/dp/B07TCGQMNH/',
                'https://www.amazon.com/SierraComfort-Electric-Massage-Table-Black/dp/B00Z9VFYCY/',
                'https://www.amazon.com/DevLon-NorthWest-Pedicure-Manicure-Adjustable/dp/B071ZR5MCV/',
                'https://www.amazon.com/Master-Massage-Mattress-Adjustable-Equipment/dp/B06X6H75FT/',
                'https://www.amazon.com/Master-Massage-Deluxe-Glider-Rolling/dp/B01M0EQO6O/',
                'https://www.amazon.com/Dr-lomilomi-Massage-Table-Supply-Rubber/dp/B0196AK6CQ/',
                'https://www.amazon.com/Barber-Fatigue-Styling-Black-Rectangle-Comfort/dp/B07J9T13HG/',
                'https://www.amazon.com/Geboor-Hydraulic-Rolling-Adjustable-Dentist/dp/B07H9RJDYZ/',
                'https://www.amazon.com/Youthful-Advantage-Cleansing-System-Replacement/dp/B00SQ821T6/',
                'https://www.amazon.com/Giantex-Adjustable-Technician-Nail-Footrest/dp/B01LX0J9RZ/',
                'https://www.amazon.com/DevLon-NorthWest-Saddle-Hydraulic-TURQUOISE/dp/B01N9X5XUF/',
                'https://www.amazon.com/SierraComfort-Universal-Shelf-Massage-Table/dp/B00KCLL0PG/',
                'https://www.amazon.com/EARTHLITE-Massage-Table-Cradle-CARESS/dp/B01LN2KAJO/',
                'https://www.amazon.com/WholeBody-Swivel-Base-Massage-Customizable-Retractable/dp/B00OJMEX9E/',
                'https://www.amazon.com/Saloniture-Adjustable-Massage-Cradle-Pillow/dp/B07G2WJXWP/',
                'https://www.amazon.com/Royal-Massage-Deluxe-Universal-Oversized/dp/B008X7SAPY/',
                'https://www.amazon.com/ZENY-Adjustable-Hydraulic-Rolling-Massage/dp/B07PLQDRMV/',
                'https://www.amazon.com/Massage-Portable-Adjustable-Headrest-KH2104S-WT/dp/B07QG5T24L/',
                'https://www.amazon.com/Massage-Pneumatic-Hydrolic-Rolling-Clinical/dp/B00QAOD8HW/',
                'https://www.amazon.com/Funnylife-Styling-Hydraulic-Shampoo-Barbering/dp/B07QVX2FL8/',
                'https://www.amazon.com/Artechworks-Wheeled-Massage-Carrying-Portable/dp/B07RWCB87L/',
                'https://www.amazon.com/Salon-Shampoo-Hair-Replacement-Sprayer/dp/B07DQ7DB2Y/',
                'https://www.amazon.com/FRNIAMC-Adjustable-Ergonomic-Hospital-Pharmacy/dp/B07LGBRZ15/',
                'https://www.amazon.com/DevLon-NorthWest-Pedicure-Adjustable-Turquoise/dp/B01MZFA4EA/',
                'https://www.amazon.com/Artist-Hand-Purpose-Hydraulic-Equipment/dp/B07W936N1M/',
                'https://www.amazon.com/Professional-Hydraulic-Recline-Stylist-Equipment/dp/B07RL5YWFR/',
                'https://www.amazon.com/BELLAVIE-Professional-Multi-purpose-Massage-Adjustable/dp/B01DOBJMZK/',
                'https://www.amazon.com/Tat-Tech-Tattoo-Black-Artists/dp/B00NDAUUQS/',
                'https://www.amazon.com/Portable-Shampoo-Adjustable-Height-Equipment/dp/B07C2XV3DR/',
                'https://www.amazon.com/Pedicure-Pneumatic-Adjustable-Furniture-Equipment/dp/B01N6SSOD2/',
                'https://www.amazon.com/DevLon-NorthWest-Saddle-Hydraulic-GrayFBA/dp/B01HBXHKYC/',
                'https://www.amazon.com/LCL-Beauty-Adjustable-Support-Equipment/dp/B00S1T7KBE/',
                'https://www.amazon.com/Performance-Kahuna-Superior-Massage-Chair/dp/B07JPZZW5B/',
                'https://www.amazon.com/Giantex-Backwash-Shampoo-Equipment-Station/dp/B01N17ZWA5/',
                'https://www.amazon.com/RetroArcade-us-ra-Stool-Black-Arcade-Adjustable-Cocktail/dp/B01E4PLSH0/',
                'https://www.amazon.com/Hydraulic-Cutting-Styling-Facial-Waxing/dp/B07D4DJLRB/',
                'https://www.amazon.com/Adjustable-Tattoo-Hydraulic-Rolling-Massage/dp/B00VWDRNRC/',
                'https://www.amazon.com/Dr-lomilomi-Hydraulic-Rolling-Massage-Backrest/dp/B07BPPR63G/',
                'https://www.amazon.com/Duhome-Leather-Working-Adjustable-Medical/dp/B078NHTNQX/',
                'https://www.amazon.com/LCL-Beauty-Mount-Shampoo-Ceramic/dp/B07N112SC5/',
                'https://www.amazon.com/Adjustable-Hairdressing-Styling-Smooth-rolling-360-degree/dp/B07KW1WCW6/',
                'https://www.amazon.com/Fatigue-Stylist-Comfort-Beauty-Semicircle-3%E2%80%B2x5%E2%80%B2x/dp/B07H4C11T4/',
                'https://www.amazon.com/Osaki-OS-4000T-Generation-Technology-Massagers/dp/B0195NEKLW/',
                'https://www.amazon.com/BarberPub-Purpose-Hydraulic-Equipment-6154-S8702BK/dp/B01N8ZKKHX/',
                'https://www.amazon.com/Sinoluck-Styling-Equipment-Hydraulic-Shampoo/dp/B07PRPXMH8/',
                'https://www.amazon.com/MAYAKOBA-Adjustable-Pneumatic-Furniture-Equipment/dp/B07SRGBC7L/',
                'https://www.amazon.com/Electronic-Extraction-COOFO-Rechargeable-Replaceable/dp/B07FQCRN7X/',
                'https://www.amazon.com/Eyebrow-Stencil-Scissors-Tweezers-Grooming/dp/B07LH38VRM/',
                'https://www.amazon.com/Blackhead-Remover-Comedone-Extractor-Removal/dp/B07PHCGCT5/',
                'https://www.amazon.com/Minso-Whitening-Remove-wrinkle-Microneedle-Titanium/dp/B07VQK9B9R/',
                'https://www.amazon.com/Upgrade-Pimple-Popper-Tool-Professional/dp/B07PCLHC1R/',
                'https://www.amazon.com/Massager-Anti-Wrinkle-Relaxing-Vibrating-Treatment/dp/B07PKMDDHJ/',
                'https://www.amazon.com/Rechargeable-Portable-Hydrating-Moisturizing-Function/dp/B072K1V527/',
                'https://www.amazon.com/Lift-Care-Euclayptus-Blackheads-Rejuvenate/dp/B0163GW1PG/',
                'https://www.amazon.com/Blackhead-CkeyiN-Upgraded-Rechargeable-Vibration/dp/B079GV5339/',
                'https://www.amazon.com/Microdermabrasion-Machine-Steamer-T3-Multi-use/dp/B00ET9KORW/',
                'https://www.amazon.com/Anyasun-Portable-Steamer-Atomization-Extensions/dp/B07KPB5H41/',
                'https://www.amazon.com/Exfoliating-Rejuvenation-Machine-Wrinkle-Dermabrasion/dp/B07JGS1HMN/',
                'https://www.amazon.com/BR-Beauty-Facial-Steamer-Magnifying/dp/B0042TN804/',
                'https://www.amazon.com/LCL-Beauty-Multifunction-Microdermabrasion-Equipment/dp/B07PMF2YY3/',
                'https://www.amazon.com/Pevor-Exfoliating-Blackhead-Rejuvenation-Anti-Aging/dp/B07BWFXCSW/',
                'https://www.amazon.com/Portable-Steamer-Hood-Humidifier-Moisturizing-Personal/dp/B07HQMWC1Z/',
                'https://www.amazon.com/Blackhead-Professional-Extractor-Treatment-Whitehead/dp/B06ZY1KH8F/',
                'https://www.amazon.com/KLOUD-City-Precision-Grooming-Different/dp/B00VSQ2K9O/',
                'https://www.amazon.com/Zeny-Diamond-Microdermabrasion-Dermabrasion-Equipment/dp/B00XGMOLU4/',
                'https://www.amazon.com/Sprayer-Machine-Wrinkle-Rejuvenation-Moisturizing/dp/B07N6YLH7Q/',
                'https://www.amazon.com/Jocasta-Facial-Steamer-Jar/dp/B004MO2TOU/',
                'https://www.amazon.com/GRUTTI-Shaving-Straight-Deluxe-Compatible/dp/B07MYWCQHH/',
                'https://www.amazon.com/Wode-Cutting-Catcher-Shaving-Trimming/dp/B07B1X8ZCZ/',
                'https://www.amazon.com/Straight-Shaving-Luxury-Professional-Shavers/dp/B07KQYVMQD/',
                'https://www.amazon.com/Luxury-Straight-Shaving-Badger-Leather/dp/B07DHFL8F3/',
                'https://www.amazon.com/Anself-Metal-Shaving-Barber-Cleaning/dp/B0734HBFS7/',
                'https://www.amazon.com/GBS-97-Natural-Shave-Soap/dp/B07KY3MKVJ/',
                'https://www.amazon.com/Best-Shavette-Straight-Razor-Replaceable/dp/B07MTRTQ57/',
                'https://www.amazon.com/Badass-Beard-Care-Essentials-Consists/dp/B07C1P7RQ4/',
                'https://www.amazon.com/Premium-Straight-Leather-Ceramic-Ultimate/dp/B07BK7JDX9/',
                'https://www.amazon.com/VIKINGS-Shaving-Gunmetal-Polished-Tortoise/dp/B07GFBS77J/',
                'https://www.amazon.com/Shaving-Catcher-Suction-Boyfriend-Gift%EF%BC%88Black%EF%BC%89/dp/B07Q2MSRKT/',
                'https://www.amazon.com/Blades-Grim-Single-Handmade-Leather/dp/B074SXCCB9/',
                'https://www.amazon.com/Men-Rock-Sandalwood-Shaving-Cream/dp/B07CV1342G/',
                'https://www.amazon.com/RazoRock-Plissoft-BRUCE-Synthetic-Shaving/dp/B01LXP3SLP/',
                'https://www.amazon.com/Grandslam-Frosted-Black-Safety-Shaving/dp/B07DMFQ3VF/',
                'https://www.amazon.com/Catcher-Shaving-Grooming-Captain-Jax/dp/B074PBB7BS/',
                'https://www.amazon.com/Magnetical-Voltage-PleasingCare-EasyFace-Cleansing/dp/B017UNCYWG/',
                'https://www.amazon.com/Michael-Soniclear-Antimicrobial-Cleansing-English/dp/B019FYF466/',
                'https://www.amazon.com/Professional-Straight-Razor-Barbers-Stainless/dp/B07MZMZ722/',
                'https://www.amazon.com/Upgraded%E3%80%91Facial-Cleansing-Merrylight-Waterproof-Rechargeable/dp/B07TLJHSWL/',
                'https://www.amazon.com/Bump-Fighter-Set-Handle-Refill/dp/B00GR1ZH72/',
                'https://www.amazon.com/Ernest-Supplies-Shaving-Box-Kit/dp/B00PHQ3DL0/',
                'https://www.amazon.com/Michael-Soniclear-Antimicrobial-Cleansing-Exfoliating/dp/B01IHAO4GU/',
                'https://www.amazon.com/MenScience-Androceuticals-Face-Buff-Brush/dp/B000AXRT24/',
                'https://www.amazon.com/1DOT2-Professional-Clippings-Grooming-Template/dp/B07F9Y6GTL/',
                'https://www.amazon.com/Michael-Soniclear-Antimicrobial-Cleansing-Exfoliating/dp/B01N01PHTY/',
                'https://www.amazon.com/BEARD-KING-Premium-Beard-Grooming/dp/B07D8FMRY8/',
                'https://www.amazon.com/Savanna-Shaving-Scuttle-Single-Mug/dp/B07STP76K9/',
                'https://www.amazon.com/Vincilee-Cleansing-Ultra-Soft-Massaging-Exfoliation/dp/B07PW5T549/',
                'https://www.amazon.com/Shaving-Kits-Gift-Set%EF%BC%8C4-Piece/dp/B07G31S797/',
                'https://www.amazon.com/Eyebrow-Razor-Shaper-Safety-Blade/dp/B07JR14LBD/',
                'https://www.amazon.com/OwnMy-Universal-Shaving-Stainless-Organizer/dp/B07J58X9TW/',
                'https://www.amazon.com/JOYSLIFE-Deluxe-Razor-Stand-Shaving/dp/B07KW7D1Y4/',
                'https://www.amazon.com/Shaving-Gillette-Replaceable-Stainless-Bowl-Perfect/dp/B075Z43NGW/',
                'https://www.amazon.com/Aysekone-DIY-Facial-Mask-Tool/dp/B07D7FB4MQ/',
                'https://www.amazon.com/Leather-Protective-Travel-Safety-RIVERLAKE/dp/B077R1BC15/',
                'https://www.amazon.com/Kibiy-Painless-Trimming-Double-Edge-Stainless/dp/B07VDKCRT1/',
                'https://www.amazon.com/Shiseido-Skincare-Cleansing-Massage-Brush/dp/B00BLG27S0/',
                'https://www.amazon.com/Michael-Soniclear-Petite-Antimicrobial-Cleansing/dp/B01IHAO140/',
                'https://www.amazon.com/Eyebrow-Foldable-Shaper-Grooming-Stencil/dp/B07TDKKKGQ/',
                'https://www.amazon.com/GABRIELLA-Womens-Eyebrows-Facial-Quantity/dp/B000EVELR8/',
                'https://www.amazon.com/Sensitive-Multi-Functional-Cleansing-Exfoliating-Exfoliate/dp/B077993JB2/',
                'https://www.amazon.com/Lansi-Magnifying-Magnification-Adjustable-Double-Sided/dp/B076Q42PB7/',
                'https://www.amazon.com/Ovente-Dual-Sided-Magnification-Electrical-MPWD3185BR1X7X/dp/B074GBLC4B/',
                'https://www.amazon.com/NiceWave-Eyebrow-Removal-produits-beautiful/dp/B07HNYTQ4G/',
                'https://www.amazon.com/RICANK-Blackhead-Cleansing-Exfoliation-Exfoliator/dp/B07H26HJJK/',
                'https://www.amazon.com/Eyebrow-Hanamichi-Tweezer-Scissor-Templates/dp/B07PFMB4GH/',
                'https://www.amazon.com/Tongtletech-Rotatable-Electric-Precision-Underarm/dp/B01N3LHOUY/',
                'https://www.amazon.com/SYBF-Silicone-Applicator-Professional-Charcoal/dp/B07PXZHPTM/',
                'https://www.amazon.com/Diane-Mirror-Medium-Assorted-Inches/dp/B00AYCO5UU/',
                'https://www.amazon.com/Sideburns-Electric-Professional-Rechargeable-Waterproof/dp/B07QHVJ7DX/',
                'https://www.amazon.com/Panasonic-Trimmer-Vacuum-Cleaning-System/dp/B07TXDYD4L/',
                'https://www.amazon.com/Boao-Pieces-Eyebrow-Trimmer-Precision/dp/B07G33841W/',
                'https://www.amazon.com/Conair-Double-Sided-Lighted-Makeup-Mirror/dp/B003GCA4TQ/',
                'https://www.amazon.com/Remington-Waterproof-Precision-Pivoting-Batteries/dp/B01B1PWBYU/',
                'https://www.amazon.com/Coobbar-Desktop-Foldable-Portable-Princess/dp/B07MBJ7RWR/',
                'https://www.amazon.com/Conair-Nose-Ear-Eyebrow-Trimmer/dp/B004RLH9I4/',
                'https://www.amazon.com/Rodan-Fields-Radiant-Defense-Liquid/dp/B07J1BC3QY/',
                'https://www.amazon.com/Rechargeable-Scrubber-Cleansing-Exfoliation-Scrubbing/dp/B07BPYKGW5/',
                'https://www.amazon.com/FOREO-LUNA-play-Cleansing-Midnight/dp/B01ESD5AC2/',
                'https://www.amazon.com/MiroPure-Cleansing-Vibration-Waterproof-Rechargeable/dp/B07LB9N1KH/',
                'https://www.amazon.com/Nose-Hair-Trimmer-Men-Double-Edge/dp/B07WNKFTYV/',
                'https://www.amazon.com/Hair-Off-Instant-Eyebrow-Shapers/dp/B00GMPAJGC/',
                'https://www.amazon.com/Etude-House-Exfoliating-Jellyfish-Silicon/dp/B071HZZVKD/',
                'https://www.amazon.com/Panasonic-Etiquette-ER-GN70-K-Domestic-Products%E3%80%91%E3%80%90Ships/dp/B07FFGYWJ6/',
                'https://www.amazon.com/Brainbow-Trimmers-Tweezers-Scissors-Stencils/dp/B07L8YNNDX/',
                'https://www.amazon.com/Upgraded%E3%80%91Gackoko-Brush-Waterproof-Heads%EF%BC%8CGentle-Exfoliating%EF%BC%8CDeep-Microdermabrasion%EF%BC%8CStimulates/dp/B07TV55MF9/',
                'https://www.amazon.com/Replacement-Zadro-Surround-Makeup-Mirror/dp/B07HJCS6BX/',
                'https://www.amazon.com/HATTEKER-Grooming-Bodygroom%EF%BC%8CNose-Men-Washable-Multi-Personal/dp/B07MXZR7LZ/',
                'https://www.amazon.com/Dozenla-Portable-Practical-Handheld-Trimmers/dp/B07W3LZ5Q7/',
                'https://www.amazon.com/Fromm-Dorco-Tinkle-Eyebrow-Shaper/dp/B079C5FQVP/',
                'https://www.amazon.com/Stiles-Eyebrow-Razor-2-Pack-Purple/dp/B00Q3K6PR8/',
                'https://www.amazon.com/Vanity-Mirror-Lights-Bluetooth-Magnification/dp/B07MJJ53M8/',
                'https://www.amazon.com/TSE-Men-Pre-Shave-Oil-Lubricating/dp/B01G4GYXKQ/',
                'https://www.amazon.com/Eyebrow-Scissors-Finger-Grips-Multi/dp/B00JH840OS/',
                'https://www.amazon.com/Magnifying-Mirror-Magnified-Application-Blackhead/dp/B07DRQVK3P/',
                'https://www.amazon.com/15X-Magnifying-Mirror-inches-Round/dp/B07CDDFYZR/',
                'https://www.amazon.com/WAYKING-Hollywood-Charging-White-2nd-Generation/dp/B07QFJTM9D/',
                'https://www.amazon.com/Jerdon-JP2027N-8-Inch-Makeup-Magnification/dp/B000G666HE/',
                'https://www.amazon.com/Miss-Sweet-Handheld-Mirror-Makeup/dp/B07BFFQB7Z/',
                'https://www.amazon.com/Williams-Lectric-Shave-Orig-7z/dp/B00EV5UW0I/',
                'https://www.amazon.com/GABELS-Instant-Liquid-Concentrated-Shaving/dp/B000UOQE3I/',
                'https://www.amazon.com/Taconic-Shave-Barbershop-Lavender-Antioxidant-Rich/dp/B012TBL3B2/',
                'https://www.amazon.com/Williams-Mug-Shaving-Soap-1-75/dp/B00B7K3PJK/',
                'https://www.amazon.com/Genuine-Ogallala-Bay-Rum-Shaving/dp/B003ZWZB9A/',
                'https://www.amazon.com/Ogallala-Bay-Rum-Rum-Limes-Peppercorns/dp/B003ZWKX1G/',
                'https://www.amazon.com/Van-Hagen-Glycerin-Shave-2-5-Ounce/dp/B075DZ492X/',
                'https://www.amazon.com/William-Mug-Soap-Size-1-75z/dp/B01IAE0A9S/',
                'https://www.amazon.com/Havana-Shave-Soap-Men-High-Performance/dp/B016CSBTS0/',
                'https://www.amazon.com/Taconic-Shave-Barbershop-Quality-Antioxidant-Rich/dp/B00L3K6H0I/',
                'https://www.amazon.com/Dr-Jons-Hex-Shaving-Soap/dp/B00R9O9CZ4/',
                'https://www.amazon.com/Aged-Spice-Origional-Fragrance-Shaving/dp/B002ZWB7YO/',
                'https://www.amazon.com/Caswell-Massey-Almond-Shave-Soap-Soothing/dp/B07KQLZK4K/',
                'https://www.amazon.com/Barristers-Reserve-Shaving-Barrister-Mann/dp/B073DD6HSS/',
                'https://www.amazon.com/GBS-97-Natural-Shave-Soap/dp/B07KY3RR21/',
                'https://www.amazon.com/Williams-Shaving-Soap-10-5-Ounce/dp/B00KJS75RE/',
                'https://www.amazon.com/Art-Shaving-TAOS-Soap-Sandalwood/dp/B000FGVJXQ/',
                'https://www.amazon.com/Mixed-Shave-Refills-Edwin-Jagger/dp/B01FMTTZBI/',
                'https://www.amazon.com/Geo-F-Trumper-Eucris-Shaving/dp/B00447O1O6/',
                'https://www.amazon.com/Van-Hagen-Luxury-Scented-Shave/dp/B004WCS7IE/',
                'https://www.amazon.com/Colonel-Conk-Model-111-scents/dp/B001XURHES/',
                'https://www.amazon.com/Towel-Warmer-Electric-Heated-Sterilizer/dp/B00CJK72PA/',
                'https://www.amazon.com/Magnifying-Compact-Mirror-10X-Magnification/dp/B07DDFHGLP/',
                'https://www.amazon.com/QIELIZI-Compact-Pocket-size-2-sided-Magnifying/dp/B07RLWGXNF/',
                'https://www.amazon.com/OMIRO-Folding-Compact-Mirror-Magnification/dp/B07B2R4SWK/',
                'https://www.amazon.com/Miss-Sweet-Compact-magnification-Magnification/dp/B074QRNYN2/',
                'https://www.amazon.com/Magnification-Rechargeable-Handheld-Dimmable-Cosmetic/dp/B07MV141QG/',
                'https://www.amazon.com/Orange-Tech-Rechargeable-Lighted-Compact/dp/B07QCRN36X/',
                'https://www.amazon.com/VISV-Magnification-Rechargeable-Portable-Foldable/dp/B07SDPH1RX/',
                'https://www.amazon.com/Lighted-Travel-Makeup-Mirror-Magnification/dp/B07VMK6XT4/',
                'https://www.amazon.com/YUSONG-Portable-Cosmetic-Folding-Compact/dp/B01C71NGJQ/',
                'https://www.amazon.com/NCToys-Compact-Mirror-Square-Makeup/dp/B07S8YM757/',
                'https://www.amazon.com/Silver-Compact-Mirror-Travel-Pocket/dp/B07PQ5HDHR/',
                'https://www.amazon.com/Ovente-Brushed-Magnification-attaches-Stainless/dp/B06XDXC8HH/',
                'https://www.amazon.com/Womens-Design-Flower-Folding-Compact/dp/B00S8QFRBU/',
                'https://www.amazon.com/Shaving-Ocean-Driftwood-Black-Ceramic/dp/B015QH383W/',
                'https://www.amazon.com/Kingsley-Silver-Plated-Shaving-Handle/dp/B00872NJU6/',
                'https://www.amazon.com/Pure-Badger-Shaving-Mens-Bowl/dp/B00SNEU49W/',
                'https://www.amazon.com/MagiDeal-Stainless-Shaving-Barber-Handle/dp/B0721216N7/',
                'https://www.amazon.com/Fine-Lather-Bowl-Shaving-Scuttle/dp/B00TEILLB6/',
                'https://www.amazon.com/Badger-Shave-Brush-shave-Simpson/dp/B003B3UAM6/',
                'https://www.amazon.com/Miusco-Shaving-Safety-Badger-Chrome/dp/B071CPRW1Q/',
                'https://www.amazon.com/Omega-Shaving-10083-Bristle-Proffessional/dp/B003DL3CKS/',
                'https://www.amazon.com/Simpson-CH1-Chubby-Badger-Shaving/dp/B00677JIZS/',
                'https://www.amazon.com/AKPOWER-Badger-Shaving-Brush/dp/B00XWDBCM2/',
                'https://www.amazon.com/Je-Co-Silvertip-Bristle-Shaving/dp/B07PWMYBCK/',
                'https://www.amazon.com/Parker-Safety-Razors-Genuine-Leather/dp/B07R39RWBS/',
                'https://www.amazon.com/Titania-Shaving-Brush-Bristle-blister/dp/B00Q56LY3U/',
                'https://www.amazon.com/MUEHLE-Shaving-Brush-Handle-Material/dp/B0040HH8V8/',
                'https://www.amazon.com/Engineered-Safety-Straight-Shaving-Lotus-flower/dp/B07DPHPJJT/',
                'https://www.amazon.com/Frank-Shaving-Pur-Tech-Synthetic-Quality/dp/B00A22XJJA/',
                'https://www.amazon.com/Yaqi-R1738-S-Purple-Synthetic-Shaving/dp/B07DCCN9K9/',
                'https://www.amazon.com/Yaqi-Silvertip-Shaving-Mountain-Handle/dp/B07VH86NBC/',
                'https://www.amazon.com/Horse-Shaving-Brush-Handle-Vie-Long/dp/B00A6SRTWS/',
                'https://www.amazon.com/Omega-63171-Stripey-Badger-Shaving/dp/B000JMFELY/',
                'https://www.amazon.com/FLOOR-Mens-Fashioned-Shave-Brush/dp/B07FFCWQ7Y/',
                'https://www.amazon.com/Semogue-2000-Natural-Bristle-Shaving/dp/B004OJQCMS/',
                'https://www.amazon.com/Grandslam-Finest-Shaving-Handle-Engineered/dp/B07D34ZDHP/',
                'https://www.amazon.com/Vtrem-Shaving-Brushes-Stainless-Perfect/dp/B07PN4W2C2/',
                'https://www.amazon.com/Bevel-Shaving-Brush-Smooth-Prevents/dp/B01M0THR37/',
                'https://www.amazon.com/Semogue-Excelsior-Handmade-Shaving-Brush/dp/B00TMOOYGQ/',
                'https://www.amazon.com/HANMIAO-Frequency-Instrument-Artifact-Professional/dp/B07TBM4PZY/',
                'https://www.amazon.com/Bestpriceam-Bottle-Applicator-Dispensing-Coloring/dp/B072NZSYSB/',
                'https://www.amazon.com/Tolco-Bottle-Frosted-Assorted-Colors/dp/B07WGNFXWQ/',
                'https://www.amazon.com/Dr-pen-Cartridges-Replacement-Consumable-Spiral/dp/B07SLRZNPJ/',
                'https://www.amazon.com/Tightening-Massager-Frequency-Vibration-Cleansing/dp/B07VB6Q792/',
                'https://www.amazon.com/Deluxe-Gold-Brush-Razor-Stand/dp/B00MRLGN0G/',
                'https://www.amazon.com/Professional-Shaving-Universal-Holder-Stainless/dp/B07GXCF87W/',
                'https://www.amazon.com/SHAVING-STAINLESS-CHROME-PERFECT-ORGANISED/dp/B01N3PDFXR/',
                'https://www.amazon.com/River-Lake-Shaving-Aluminum-included/dp/B075XLW3N8/',
                'https://www.amazon.com/Muehle-Crystal-Shaving-Brush-Holder/dp/B0006O4NS0/',
                'https://www.amazon.com/Anself-Stainless-Shaving-Holder-Organizer/dp/B06VSH49BG/',
                'https://www.amazon.com/QShave-Deluxe-Chrome-Shaving-Accessories/dp/B07431KWBC/',
                'https://www.amazon.com/Portable-Chrome-Shaving-Refined-Curved/dp/B07NYPCLDL/',
                'https://www.amazon.com/GRUTTI-Deluxe-Chrome-Holder-Shaving-Gold/dp/B07K7JMKYG/',
                'https://www.amazon.com/Stainless-Steel-Razor-Shaving-Stand/dp/B00GMNZHW0/',
                'https://www.amazon.com/HongLanAo-Shaving-Additional-Facilitates-Hygiene/dp/B07HSWP4K2/',
                'https://www.amazon.com/VIGSHAVING-Leather-Sharpening-Shaving-Straight/dp/B014XL86NE/',
                'https://www.amazon.com/Cleancut-Personal-Electric-Shaver-Trimmer/dp/B07KPT784T/',
                'https://www.amazon.com/Canoe-After-Shave-Splash-Dana/dp/B0010E6TMI/',
                'https://www.amazon.com/Gillette-CustomPlus-Disposable-Razor-Sensitive/dp/B071FH2X2B/',
                'https://www.amazon.com/Whish-Flawless-Post-Shave-Serum/dp/B002IY79HI/',
                'https://www.amazon.com/Remington-BHT250-Piece-Grooming-Black/dp/B06WRR1RZL/',
                'https://www.amazon.com/Gillette-Lotion-Sensitive-Razors-Blades/dp/B001E95HFO/',
                'https://www.amazon.com/Captain-Fawcetts-Moustache-Wax-Lavender/dp/B00JGRX97O/',
                'https://www.amazon.com/Old-Spice-Classic-After-Shave/dp/B00BVO8FLK/',
                'https://www.amazon.com/Haofy-Electric-Portable-Handheld-Battery-operated/dp/B07T7JNNNL/',
                'https://www.amazon.com/FLORIDA-WATER-PLASTIC-BOTTLE-Pack/dp/B006QSOXVW/',
                'https://www.amazon.com/Aveda-After-Shave-2-5-Ounce/dp/B0051RY6AC/',
                'https://www.amazon.com/Mr-Bear-Family-Moustache-1-01oz/dp/B06XGS1F1C/',
                'https://www.amazon.com/Brut-After-Shave-Lotion-Original/dp/B00J5J2Z00/',
                'https://www.amazon.com/Clubman-Moustache-Neutral-0-50-Pack/dp/B01IA9FDU4/',
                'https://www.amazon.com/Woodys-Mens-Grooming-After-Shave/dp/B01FN8IOG0/',
                'https://www.amazon.com/Clubman-Pinauds-classic-fragrance-Soothes/dp/B01GLVZEFM/',
                'https://www.amazon.com/Scissors-Stainless-Mustache-Eyebrow-HAWATOUR/dp/B07VH48CQF/',
                'https://www.amazon.com/ECO-WORTHY-Portable-Aesthetic-Clinicians-Diagnosis/dp/B074SFPWSK/',
                'https://www.amazon.com/MenScience-Androceuticals-Advanced-Shave-Formula/dp/B0002ZOF2M/',
                'https://www.amazon.com/Taylor-Old-Bond-Street-Sandalwood/dp/B00FKXP8C2/',
                'https://www.amazon.com/Freshscent-Shaving-Cream-Packs-0-25oz/dp/B00H4FH5VQ/',
                'https://www.amazon.com/Taylor-Old-Bond-Street-Grapefruit/dp/B00BPAO48S/',
                'https://www.amazon.com/Dorco-Shaving-System-Handle-Cartridges/dp/B00R4AM3TU/',
                'https://www.amazon.com/Peace-Smooth-Things-Ounces-2-Pack/dp/B00XWI2JZQ/',
                'https://www.amazon.com/Pre-Shave-Gel-Jermyn-Street-Collection/dp/B009HUD4S4/',
                'https://www.amazon.com/Project-Beauty-Frequency-Galvanic-Machine/dp/B008JYGVT8/',
                'https://www.amazon.com/Taylor-Old-Bond-Street-Organic/dp/B00ODCJBAQ/',
                'https://www.amazon.com/Pevor-Portable-Intensity-Rejuvenation-Wrinkles/dp/B07H92JWCP/',
                'https://www.amazon.com/Hydraskincare-Frequency-Tightening-Multipolar-Rejuvenation/dp/B07R229VJY/',
                'https://www.amazon.com/GILLETTTE-FOAMY-SHAVING-CREAM-REGULAR/dp/B00589BC0U/',
                'https://www.amazon.com/Premium-Razors-Handle-4-Blade-SWIPE/dp/B06XPRFK9X/',
                'https://www.amazon.com/HeadBlade-ATX-Headshaver-with-HeadCase/dp/B07999TQ5Y/',
                'https://www.amazon.com/UMTYPE-Effects-Machine-juvenation-Tightening/dp/B07VRR79RV/',
                'https://www.amazon.com/Yuniole-Shaving-Blades-Knives-Razors/dp/B07VSGKHK3/',
                'https://www.amazon.com/Harrys-Mens-Razor-Blades-Forest/dp/B01MSCM9YI/',
                'https://www.amazon.com/St-James-London-Sandalwood-Bergamot/dp/B00PCZ2FG0/',
                'https://www.amazon.com/Curved-Stand-Chrome-Straight-Razors/dp/B00EUMDO2A/',
                'https://www.amazon.com/Campbells-Pre-Mixed-Shave-Cream-64oz/dp/B07623WQQD/',
                'https://www.amazon.com/Every-Man-Jack-Sensitive-Shave/dp/B00J5IWX5S/',
                'https://www.amazon.com/Taylor-Old-Bond-Street-Sandalwood/dp/B0015G3YMO/',
                'https://www.amazon.com/Biodegradable-Handle-Razors-Three-Blades/dp/B07M5PQX1Q/',
                'https://www.amazon.com/Personna-Twin-Pivot-Lubricating-Strip/dp/B002A6KFI4/',
                'https://www.amazon.com/Jatai-Feather-Styling-Replacement-Blades/dp/B0009G0HUS/',
                'https://www.amazon.com/Edwin-Jagger-Double-Safety-Razor/dp/B003LW4LJK/',
                'https://www.amazon.com/Every-Man-Jack-Razor-Cartridges/dp/B00X63CRCM/',
                'https://www.amazon.com/Parker-Three-Safety-Razor-Premium/dp/B00IDDW4Y6/',
                'https://www.amazon.com/Straight-without-stabilizer-straight-acrylic/dp/B07515QTX9/',
                'https://www.amazon.com/Manual-Shaver-Replacement-Cartridges-Shaving/dp/B07PQMPP2R/',
                'https://www.amazon.com/Schick-Xtreme-Senstive-Disposable-Heavyweight/dp/B07DQXXJY4/',
                'https://www.amazon.com/Professional-Plastic-Shaving-Straight-Folding/dp/B07JVVJ3BB/',
                'https://www.amazon.com/QSHAVE-Portable-Protector-Suitable-ProGlide/dp/B07JYZ41LG/',
                'https://www.amazon.com/Astra-Derby-Shark-Lord-Treet-Voskhod-Rapira-Quality-Razor-Blades-different/dp/B07RTM9NB5/',
                'https://www.amazon.com/Twin-Select-Mens-Size-10ct/dp/B01IADVGYW/',
                'https://www.amazon.com/Fashion-Cartridages-1Manual-Replacement-Cartriges/dp/B07RDFXT7F/',
                'https://www.amazon.com/Sticker-Metallic-Temporary-Transfer-Professional/dp/B0777QPD9Z/',
                'https://www.amazon.com/Vincent-58mm-Single-Razor-VT302/dp/B00AQOIO2Q/',
                'https://www.amazon.com/MERKUR-Slant-MK-39C-Double-Safety/dp/B002CLH5MG/',
                'https://www.amazon.com/Personna-Pivot-Blades-Trac2-Razors/dp/B00954O15C/',
                'https://www.amazon.com/Classic-Professional-Straight-Universal-Disposable/dp/B07NRX33HW/',
                'https://www.amazon.com/Tach-Single-Industrial-Razor-Blade/dp/B07QFRP635/',
                'https://www.amazon.com/DOVO-Knives-985810-Straight-Closed/dp/B000Q85OJS/',
                'https://www.amazon.com/Shavette-Blade-Holder-Transparent-Dv-201013/dp/B00I2SJXJG/',
                'https://www.amazon.com/Parker-Womens-Butterfly-Safety-Razor/dp/B013S2GKJQ/',
                'https://www.amazon.com/MD-Sicilian-Razor-Exposed-Blade/dp/B00FRS09WE/',
                'https://www.amazon.com/Parkers-Safety-Razor-Parker-Premium/dp/B07T4TH917/',
                'https://www.amazon.com/Straight-Professional-Shaving-Tattoos-Universal/dp/B07P5NH2MJ/',
                'https://www.amazon.com/Gillette-Double-Platinum-Razors-Blades/dp/B01AL2OZGQ/',
                'https://www.amazon.com/Perma-Sharp-Double-Safety-Blades-display/dp/B009BS5CUA/',
                'https://www.amazon.com/different-Metallic-Temporary-Transfer-Professional/dp/B07VYY25N5/',
                'https://www.amazon.com/Dovo-DOV201081-DOVO-Straight-Razor/dp/B009ZQHIWI/',
                'https://www.amazon.com/Braun-81314663-Station-350cc-4-Compatible/dp/B07WNQZN6Q/',
                'https://www.amazon.com/Classic-Professional-Straight-Universal-Disposable/dp/B07NQMVP3X/',
                'https://www.amazon.com/Hraindrop-25Sheets-Temporary-Birthday-Supplies/dp/B07DYPGNH4/',
                'https://www.amazon.com/Replacement-Protection-Cleaning-Replacing-Philips/dp/B07QYLH6K9/',
                'https://www.amazon.com/Herold-Solingen-Linen-Sharpening-Germany/dp/B077SNV5DL/'
                ]
    for product in products:
        product_url = product
        # product_url = product[3]
        # print("'" + product_url + "',")
        get_amz_cookies(product_url)
        time.sleep(10)


if __name__ == '__main__':
    main()
